"""Load Wazuh alerts and vulnerability state into the Watchtide SQL warehouse.

Usage (from the repo root):
    .venv\\Scripts\\python.exe loader\\wazuh_to_sql.py

Reads settings from loader/.env (see .env.example). The Wazuh Indexer only
listens on the VM's loopback address, so each run opens an SSH tunnel with a
key that the VM restricts to forwarding 127.0.0.1:9200. Each run then:
  1. pulls recent alerts with a small overlap and reconciles all retained alert
     indices at least daily (or with --reconcile) to recover late-indexed alerts,
  2. inserts only alerts whose Indexer _id is not already stored,
  3. replaces today's vulnerability snapshot from wazuh-states-vulnerabilities-*,
  4. extracts vulnerability and CIS benchmark events from the new alerts,
  5. refreshes the permanent daily summaries and applies Low-severity retention,
  6. records the outcome in sg.load_runs.
Re-running is always safe: duplicates are skipped by document ID.
"""

import argparse
import json
import os
import socket
import ssl
import subprocess
import sys
import time
from contextlib import contextmanager
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pyodbc
import requests
from requests.adapters import HTTPAdapter

ENV_FILE = Path(__file__).parent / ".env"
PAGE_SIZE = 1000
OVERLAP = timedelta(minutes=10)
RECONCILE_INTERVAL = timedelta(days=1)
ALERTS_INDEX = "wazuh-alerts-*"
VULNS_INDEX = "wazuh-states-vulnerabilities-*"
VULNS_MAX = 10000


@contextmanager
def ssh_tunnel(settings: dict):
    """Forward a local port to the Indexer, which only listens on the VM's
    loopback address. The key is restricted on the VM to this one forward."""
    target = settings.get("SSH_TUNNEL_TARGET")
    if not target:
        yield
        return
    local_port = int(settings.get("SSH_TUNNEL_LOCAL_PORT", "19200"))
    proc = subprocess.Popen(
        [
            "ssh", "-N",
            "-L", f"{local_port}:127.0.0.1:9200",
            "-i", settings["SSH_KEY_FILE"],
            "-o", "BatchMode=yes",
            "-o", "ExitOnForwardFailure=yes",
            "-o", "StrictHostKeyChecking=accept-new",
            target,
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )
    try:
        deadline = time.monotonic() + 20
        while True:
            if proc.poll() is not None:
                raise RuntimeError(f"SSH tunnel failed: {proc.stderr.read().decode(errors='replace').strip()}")
            try:
                socket.create_connection(("127.0.0.1", local_port), timeout=1).close()
                break
            except OSError:
                if time.monotonic() > deadline:
                    raise RuntimeError("SSH tunnel did not open within 20 seconds")
                time.sleep(0.5)
        yield
    finally:
        proc.terminate()
        proc.wait(timeout=10)


def load_settings() -> dict:
    """Read KEY=VALUE lines from loader/.env; real environment variables win."""
    settings = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                settings[key.strip()] = value.strip()
    for key in list(settings) + ["WAZUH_INDEXER_PASSWORD"]:
        if key in os.environ:
            settings[key] = os.environ[key]
    required = ["WAZUH_INDEXER_URL", "WAZUH_INDEXER_USER", "WAZUH_INDEXER_PASSWORD", "WAZUH_CA_FILE"]
    missing = [k for k in required if not settings.get(k)]
    if missing:
        raise SystemExit(f"Missing settings in {ENV_FILE}: {', '.join(missing)}")
    return settings


class WazuhCAAdapter(HTTPAdapter):
    """Trust only the Wazuh root CA, with chain and hostname checks on.

    Python 3.13+ turns on strict X.509 checking by default, which rejects the
    root CA generated by the Wazuh installer because it lacks a keyUsage
    extension. Only that strict-mode flag is cleared; verification stays on.
    """

    def __init__(self, ca_file: str, **kwargs):
        self.ssl_context = ssl.create_default_context(cafile=ca_file)
        self.ssl_context.verify_flags &= ~ssl.VERIFY_X509_STRICT
        super().__init__(**kwargs)

    def init_poolmanager(self, *args, **kwargs):
        kwargs["ssl_context"] = self.ssl_context
        super().init_poolmanager(*args, **kwargs)


class Indexer:
    def __init__(self, settings: dict):
        self.url = settings["WAZUH_INDEXER_URL"].rstrip("/")
        self.session = requests.Session()
        self.session.auth = (settings["WAZUH_INDEXER_USER"], settings["WAZUH_INDEXER_PASSWORD"])
        self.session.mount("https://", WazuhCAAdapter(settings["WAZUH_CA_FILE"]))

    def search(self, index: str, body: dict) -> dict:
        resp = self.session.post(
            f"{self.url}/{index}/_search", json=body, timeout=60,
            params={"allow_no_indices": "false", "ignore_unavailable": "false"},
        )
        resp.raise_for_status()
        result = resp.json()
        if result.get("timed_out") or result.get("_shards", {}).get("failed", 0):
            raise RuntimeError("Indexer search was incomplete; warehouse state preserved")
        if result.get("_shards", {}).get("total") == 0:
            raise RuntimeError("Indexer search matched no shards; warehouse state preserved")
        return result


def parse_ts(value: str) -> datetime:
    """Wazuh timestamps look like 2026-09-30T08:46:59.123+0000. Return naive UTC."""
    return datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%f%z").astimezone(timezone.utc).replace(tzinfo=None)


def dig(doc: dict, path: str):
    for part in path.split("."):
        if not isinstance(doc, dict):
            return None
        doc = doc.get(part)
    return doc


def unescape(value):
    """Wazuh's Windows decoder keeps JSON-style escaping inside eventdata strings
    (C:\\\\Windows, \\"quoted\\"). Store the paths and commands as Windows shows them.
    Keep in sync with the backfill in warehouse/sql/04_backfill_unescape.sql."""
    if not isinstance(value, str):
        return value
    return value.replace("\\\\", "\\").replace('\\"', '"')


def to_int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def get_watermark(cur, *, reconcile=False, now=None) -> datetime | None:
    now = now or datetime.now(timezone.utc).replace(tzinfo=None)
    if reconcile:
        return None
    last_full = cur.execute(
        "SELECT MAX(finished_at_utc) FROM sg.load_runs WHERE status = 'succeeded' AND watermark_from IS NULL"
    ).fetchone()[0]
    if last_full is None or now - last_full >= RECONCILE_INTERVAL:
        return None
    row = cur.execute("SELECT MAX(alert_ts_utc) FROM sg.alerts").fetchone()
    return min(row[0], now) - OVERLAP if row and row[0] else None


def fetch_alert_pages(indexer: Indexer, since: datetime | None):
    """Yield pages of alert hits in timestamp order, using search_after paging."""
    query = {"match_all": {}}
    if since:
        query = {"range": {"timestamp": {"gte": since.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"}}}
    body = {
        "size": PAGE_SIZE,
        "query": query,
        "sort": [{"timestamp": "asc"}, {"id": "asc"}],
    }
    while True:
        hits = indexer.search(ALERTS_INDEX, body)["hits"]["hits"]
        if not hits:
            return
        yield hits
        if len(hits) < PAGE_SIZE:
            return
        body["search_after"] = hits[-1]["sort"]


def load_alert_page(cur, hits: list) -> int:
    ids = [h["_id"] for h in hits]
    placeholders = ",".join("?" * len(ids))
    existing = {r[0] for r in cur.execute(f"SELECT doc_id FROM sg.alerts WHERE doc_id IN ({placeholders})", ids)}
    new_hits = [h for h in hits if h["_id"] not in existing]

    for h in new_hits:
        src = h["_source"]
        ts = parse_ts(src["timestamp"])
        agent_id = str(dig(src, "agent.id") or "unknown")
        rule_id = to_int(dig(src, "rule.id")) or 0
        rule_level = to_int(dig(src, "rule.level")) or 0
        rule_desc = unescape(dig(src, "rule.description") or "")   # some embed event paths
        groups = dig(src, "rule.groups") or []

        cur.execute(
            """MERGE sg.agents AS t
               USING (SELECT ? AS agent_id, ? AS agent_name, ? AS agent_ip, ? AS ts) AS s
               ON t.agent_id = s.agent_id
               WHEN MATCHED THEN UPDATE SET agent_name = s.agent_name,
                    agent_ip = COALESCE(s.agent_ip, t.agent_ip),
                    last_seen_utc = CASE WHEN s.ts > t.last_seen_utc THEN s.ts ELSE t.last_seen_utc END
               WHEN NOT MATCHED THEN INSERT (agent_id, agent_name, agent_ip, first_seen_utc, last_seen_utc)
                    VALUES (s.agent_id, s.agent_name, s.agent_ip, s.ts, s.ts);""",
            agent_id, dig(src, "agent.name") or agent_id, dig(src, "agent.ip"), ts,
        )
        cur.execute(
            """MERGE sg.rules AS t
               USING (SELECT ? AS rule_id, ? AS description, ? AS rule_level, ? AS rule_groups, ? AS ts) AS s
               ON t.rule_id = s.rule_id
               WHEN MATCHED THEN UPDATE SET description = s.description, rule_level = s.rule_level,
                    rule_groups = s.rule_groups,
                    last_seen_utc = CASE WHEN s.ts > t.last_seen_utc THEN s.ts ELSE t.last_seen_utc END
               WHEN NOT MATCHED THEN INSERT (rule_id, description, rule_level, rule_groups, first_seen_utc, last_seen_utc)
                    VALUES (s.rule_id, s.description, s.rule_level, s.rule_groups, s.ts, s.ts);""",
            rule_id, rule_desc, rule_level, ",".join(groups), ts,
        )
        cur.execute(
            """INSERT INTO sg.alerts (doc_id, index_name, wazuh_alert_id, alert_ts_utc, agent_id, rule_id,
                   rule_level, rule_description, event_channel, win_event_id, process_image, parent_image,
                   command_line, target_filename, user_name, raw_json)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            h["_id"], h["_index"], src.get("id"), ts, agent_id, rule_id, rule_level, rule_desc,
            dig(src, "data.win.system.channel"),
            to_int(dig(src, "data.win.system.eventID")),
            unescape(dig(src, "data.win.eventdata.image")),
            unescape(dig(src, "data.win.eventdata.parentImage")),
            unescape(dig(src, "data.win.eventdata.commandLine")),
            unescape(dig(src, "data.win.eventdata.targetFilename")),
            unescape(dig(src, "data.win.eventdata.user")),
            json.dumps(src, ensure_ascii=False),
        )

        mitre_ids = dig(src, "rule.mitre.id") or []
        mitre_names = dig(src, "rule.mitre.technique") or []
        for i, technique_id in enumerate(mitre_ids):
            name = mitre_names[i] if i < len(mitre_names) else technique_id
            cur.execute(
                """IF NOT EXISTS (SELECT 1 FROM sg.mitre_techniques WHERE technique_id = ?)
                       INSERT INTO sg.mitre_techniques (technique_id, technique_name) VALUES (?, ?)""",
                technique_id, technique_id, name,
            )
            cur.execute(
                """IF NOT EXISTS (SELECT 1 FROM sg.alert_techniques WHERE doc_id = ? AND technique_id = ?)
                       INSERT INTO sg.alert_techniques (doc_id, technique_id) VALUES (?, ?)""",
                h["_id"], technique_id, h["_id"], technique_id,
            )
        for tactic in set(dig(src, "rule.mitre.tactic") or []):
            cur.execute("INSERT INTO sg.alert_tactics (doc_id, tactic) VALUES (?, ?)", h["_id"], tactic)

    return len(new_hits)


def snapshot_vulnerabilities(cur, indexer: Indexer) -> int:
    """Replace today's vulnerability snapshot with the Indexer's current state."""
    result = indexer.search(VULNS_INDEX, {"size": VULNS_MAX, "track_total_hits": True,
                                       "query": {"match_all": {}}})
    hits = result["hits"]["hits"]
    total = result["hits"].get("total")
    if not isinstance(total, dict) or total.get("relation") != "eq" or total.get("value") != len(hits):
        raise RuntimeError("Vulnerability snapshot is incomplete; previous snapshot preserved")

    today = date.today()
    cur.execute("DELETE FROM sg.vulnerability_snapshots WHERE snapshot_date = ?", today)
    seen = set()
    for h in hits:
        src = h["_source"]
        agent_id = str(dig(src, "agent.id") or "unknown")
        key = (agent_id, dig(src, "vulnerability.id"), dig(src, "package.name"), dig(src, "package.version") or "")
        if None in key or key in seen:
            continue
        seen.add(key)
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        cur.execute(
            """IF NOT EXISTS (SELECT 1 FROM sg.agents WHERE agent_id = ?)
                   INSERT INTO sg.agents (agent_id, agent_name, first_seen_utc, last_seen_utc) VALUES (?, ?, ?, ?)""",
            agent_id, agent_id, dig(src, "agent.name") or agent_id, now, now,
        )
        detected = dig(src, "vulnerability.detected_at")
        cur.execute(
            """INSERT INTO sg.vulnerability_snapshots (snapshot_date, agent_id, cve_id, package_name,
                   package_version, severity, base_score, detected_at_utc)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            today, *key, dig(src, "vulnerability.severity") or "Unknown",
            dig(src, "vulnerability.score.base"),
            parse_iso(detected) if detected else None,
        )
    return len(seen)


def parse_iso(value: str) -> datetime | None:
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc).replace(tzinfo=None)
    except ValueError:
        return None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reconcile", action="store_true", help="rescan every alert still retained by the Indexer")
    args = parser.parse_args(argv)
    settings = load_settings()
    conn = pyodbc.connect(settings.get(
        "SQL_CONNECTION_STRING",
        "Driver={ODBC Driver 18 for SQL Server};Server=localhost;Database=SentinelGridWarehouse;"
        "Trusted_Connection=yes;TrustServerCertificate=yes",
    ))
    cur = conn.cursor()
    started = datetime.now(timezone.utc).replace(tzinfo=None)
    run_id = cur.execute(
        "INSERT INTO sg.load_runs (started_at_utc, status) OUTPUT INSERTED.run_id VALUES (?, 'running')", started
    ).fetchone()[0]
    conn.commit()

    watermark = None
    summary_from = None
    fetched = inserted = vulns = 0
    try:
        watermark = get_watermark(cur, reconcile=args.reconcile)
        with ssh_tunnel(settings):
            indexer = Indexer(settings)
            for page in fetch_alert_pages(indexer, watermark):
                fetched += len(page)
                added = load_alert_page(cur, page)
                inserted += added
                if added:
                    # A conservative UTC date includes the preceding Eastern day.
                    page_from = min(parse_ts(hit["_source"]["timestamp"]) for hit in page).date() - timedelta(days=1)
                    summary_from = min(summary_from, page_from) if summary_from else page_from
                conn.commit()
            vulns = snapshot_vulnerabilities(cur, indexer)
            conn.commit()
        # Posture (warehouse/sql/06_posture.sql): extract vulnerability and CIS
        # benchmark events from the new alerts while their raw JSON is present.
        cur.execute("EXEC sg.refresh_posture_events")
        # Lifecycle (warehouse/sql/05_lifecycle.sql): roll recent days into the
        # permanent daily summaries, then trim or delete old Low-severity detail.
        cur.execute("EXEC sg.refresh_daily_summary @from_date = ?", summary_from)
        cur.execute("EXEC sg.apply_retention").fetchall()
        conn.commit()
        status, error = "succeeded", None
    except Exception as exc:  # recorded in sg.load_runs, then re-raised for the exit code
        conn.rollback()
        status, error = "failed", f"{type(exc).__name__}: {exc}"

    cur.execute(
        """UPDATE sg.load_runs SET finished_at_utc = ?, status = ?, watermark_from = ?,
               watermark_to = (SELECT MAX(alert_ts_utc) FROM sg.alerts),
               alerts_fetched = ?, alerts_inserted = ?, vulns_snapshotted = ?, error_message = ?
           WHERE run_id = ?""",
        datetime.now(timezone.utc).replace(tzinfo=None), status, watermark, fetched, inserted, vulns, error, run_id,
    )
    conn.commit()
    print(f"run {run_id} {status}: fetched {fetched}, inserted {inserted}, vulnerabilities {vulns}")
    if error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
